baseURL = 'https://CharlieFZ.github.io/'
languageCode = 'zh-cn'
title = "Charlie's Research Blog"
theme = 'PaperMod'
paginate = 10

[params]
  description = "AI4Science | Bioinformatics | 科研思考"
  author = "Charlie FZ"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  showToc = true
  TocOpen = false
  defaultTheme = "light"
  disableThemeToggle = false

  [params.homeInfoParams]
    Title = "Charlie's Research Blog"
    Content = "AI4Science | Bioinformatics | 科研笔记与方法论反思"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/CharlieFZ"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:fangkeyi985@gmail.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github"
  lineNos = false
